Multiple source dirs
FedericoPonzi/Horust pull request #56
Opened 2021-04-22 22:02 UTC by frondeus

### Motivation and Context

Fixes #55 

### Description
* Change --service-path to accept multiple `PathBuf`
* Add `Horust::fetch_service_dirs` method
* Keep in memory list of directories, not an option

### How Has This Been Tested?

For now, tested manually. I have to prepare integration test for that feature.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2021-04-23 16:24 UTC, FedericoPonzi commented
Awesome job, thanks!

2021-04-23 16:39 UTC, FedericoPonzi requested changes
Just one typo, otherwise LGTM

2021-04-23 16:39 UTC, FedericoPonzi commented on DOCUMENTATION.md
> +Horust supports more than one service directory by accepting more than one `--services-path` arguemts.
```suggestion
Horust supports more than one service directory by accepting more than one `--services-path` arguments.
```

2021-04-23 16:51 UTC, merged

2021-04-26 11:06 UTC, esavier commented
@FedericoPonzi can we expect cargo release somewhere soon?

2021-04-26 11:15 UTC, FedericoPonzi commented
@esavier I've just pushed the latest cargo release (0.1.3) thanks!